import enum


class IgrsDeedStatus(enum.Enum):
    REGISTERED = "REGISTERED"
    NOT_MATCHED = "N"
    NOT_FOUND = "NOT_FOUND"


class IgrsFailureReason(enum.Enum):
    NO_SUCH_DEED = "NO_SUCH_DEED"
    PARTY_MISMATCH = "PARTY_MISMATCH"


class IgrsRequestError(enum.Enum):
    API_KEY_REQUIRED = "API_KEY_REQUIRED"
    API_KEY_INVALID = "API_KEY_INVALID"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    DOCUMENT_NUMBER_REQUIRED = "DOCUMENT_NUMBER_REQUIRED"
    DOCUMENT_NUMBER_MALFORMED = "DOCUMENT_NUMBER_MALFORMED"
    NAME_REQUIRED = "NAME_REQUIRED"
    UNKNOWN_DEMO_OUTCOME = "UNKNOWN_DEMO_OUTCOME"
    DEMO_OUTCOME_NOT_PERMITTED = "DEMO_OUTCOME_NOT_PERMITTED"


class IgrsServerError(enum.Enum):
    IGRS_UNAVAILABLE = "IGRS_UNAVAILABLE"
