import enum

from mock_issuer_services.constants.issuer_http_constants import (  # noqa: F401
    API_KEY_HEADER,
    BAD_REQUEST_STATUS,
    DEMO_OUTCOME_HEADER,
    SERVICE_UNAVAILABLE_STATUS,
    UNAUTHORISED_STATUS,
    DemoOutcome,
)

REFERENCE_ID_PREFIX = "ITD"
REFERENCE_ID_LENGTH = 12


class ItdVerificationStatus(enum.Enum):
    VALID = "VALID"
    NOT_MATCHED = "N"
    NOT_FOUND = "NOT_FOUND"


class ItdFailureReason(enum.Enum):
    NO_SUCH_PAN = "NO_SUCH_PAN"
    DEMOGRAPHIC_MISMATCH = "DEMOGRAPHIC_MISMATCH"


class ItdRequestError(enum.Enum):
    API_KEY_REQUIRED = "API_KEY_REQUIRED"
    API_KEY_INVALID = "API_KEY_INVALID"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    PAN_REQUIRED = "PAN_REQUIRED"
    PAN_MALFORMED = "PAN_MALFORMED"
    NAME_REQUIRED = "NAME_REQUIRED"
    UNKNOWN_DEMO_OUTCOME = "UNKNOWN_DEMO_OUTCOME"
    DEMO_OUTCOME_NOT_PERMITTED = "DEMO_OUTCOME_NOT_PERMITTED"


class ItdServerError(enum.Enum):
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
