import enum


class SarathiLicenceStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    NOT_MATCHED = "N"
    NOT_FOUND = "NOT_FOUND"


class SarathiFailureReason(enum.Enum):
    NO_SUCH_LICENCE = "NO_SUCH_LICENCE"
    HOLDER_MISMATCH = "HOLDER_MISMATCH"


class SarathiRequestError(enum.Enum):
    API_KEY_REQUIRED = "API_KEY_REQUIRED"
    API_KEY_INVALID = "API_KEY_INVALID"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    LICENCE_REQUIRED = "LICENCE_REQUIRED"
    LICENCE_MALFORMED = "LICENCE_MALFORMED"
    NAME_REQUIRED = "NAME_REQUIRED"
    UNKNOWN_DEMO_OUTCOME = "UNKNOWN_DEMO_OUTCOME"
    DEMO_OUTCOME_NOT_PERMITTED = "DEMO_OUTCOME_NOT_PERMITTED"


class SarathiServerError(enum.Enum):
    SARATHI_UNAVAILABLE = "SARATHI_UNAVAILABLE"
